services:

  postgres:
    image: postgres:17
    container_name: metaFoodCraftPostgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - metaFoodCraftData:/var/lib/postgresql/data

volumes:
  metaFoodCraftData:
